name: Sync JVChat_Premium to debug
# .github/workflows/copy_branch.yml
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync to fork-of-fork and debug
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          for branch in fork-of-fork debug; do
            git checkout $branch

            curl -L "https://update.greasyfork.org/scripts/576263.user.js" \
                          -o raw.user.js

            VERSION=$(grep '// @version' raw.user.js | awk '{print $NF}')

            awk '/^\/\/ ==UserScript==/{skip=1} /^\/\/ ==\/UserScript==/{skip=0;next} !skip{print}' \
              raw.user.js > body.js

            echo '// ==UserScript==' > new_header.js
            echo '// @name           JV_Chat_Custsom_Fork' >> new_header.js
            echo '// @description    Outil de discussion instantanée (Fork et debug)' >> new_header.js
            echo '// @author         Blaff, Rand0max, Atlantis' >> new_header.js
            echo '// @namespace      JV_Chat_Custsom_Fork' >> new_header.js
            echo '// @license        MIT' >> new_header.js
            echo "// @version        $VERSION" >> new_header.js
            echo '// @icon           https://images.emojiterra.com/google/noto-emoji/unicode-17.0/color/128px/2b1b.png' >> new_header.js
            echo '// @match          http://*.jeuxvideo.com/forums/42-*' >> new_header.js
            echo '// @match          https://*.jeuxvideo.com/forums/42-*' >> new_header.js
            echo '// @match          http://*.jeuxvideo.com/forums/1-*' >> new_header.js
            echo '// @match          https://*.jeuxvideo.com/forums/1-*' >> new_header.js
            echo '// @downloadURL https://update.greasyfork.org/scripts/576263/JV_Chat_Custsom_Fork.user.js' >> new_header.js
            echo '// @updateURL https://update.greasyfork.org/scripts/576263/JV_Chat_Custsom_Fork.meta.js' >> new_header.js
            echo '// ==/UserScript==' >> new_header.js

            cat new_header.js body.js > JVChat_Premium.user.js
            rm raw.user.js body.js new_header.js

            git add JVChat_Premium.user.js
            git commit -m "push" || echo "Rien à committer sur $branch"
            git push origin $branch
          done
