name: Push commit
# .github/workflows/copy_branch.yml
on:
  workflow_dispatch:

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Nom commit'
        required: false
        default: 'push'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync to fork-of-fork and debug
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          cp .github/workflows/copy_branch_patch_header.py /tmp/patch_header.py
          for branch in fork-of-fork debug; do
            git checkout $branch

            curl -L "https://update.greasyfork.org/scripts/471322.user.js" -o raw.user.js
            python3 /tmp/patch_header.py raw.user.js JVChat_Premium.user.js
            rm raw.user.js

            git add JVChat_Premium.user.js
            git commit -m "${{ github.event.inputs.commit_message }}" || echo "Rien à committer sur $branch"
            git push origin $branch
          done
